[env]
platform = teensy
board = teensy40
framework = arduino
lib_deps = askuric/Simple FOC@^2.3.4

# Run with "pio run -e encoder_test"
[env:encoder_test]
build_src_filter = +<encoder_test/>

# Run with "pio run -e openloop_angle"
[env:openloop_angle]
build_src_filter = +<openloop_angle/>